### ISSUE TITLE
extra option for block devices

### ISSUE THREAD

**Issue by finasfinas** [ArchipelProject/Archipel#1133] opened 2015-04-19 22:51 UTC
There is a very important tunabble that I would love to  be able to change from the archipel interface and it is the io="value" directive. it can be either native or threads.

**Comment by CyrilPeponnet** [comment] 2015-04-19 23:16
Duplicate of #817.

You can tweak it directly in the xml definition if needed.

**Closed by CyrilPeponnet** 2015-04-19 23:16 UTC
Labels: #duplicate

**Comment by finasfinas** [comment] 2015-04-19 23:21
I know that. but it would be much more clean to do in in archipel. plus, tweaking the xml is a pain because anything I change on the xlm gets lost if I do something else in archipel. and it's such a easy thing to implement that I see no reason to not use it!!! it's just an extra option next the cache options on the block devices!

**Comment by CyrilPeponnet** [comment] 2015-04-19 23:22
Sure pull requests are welcome :)
